Task 02
Teaching-projects/SZE-MOSZE-2020-Insert_name_here pull request #2
Opened 2020-09-23 17:13 UTC by mogyorosimartin

Modified the code to work with json files, added units directory and unit json files, added a script that validates output.

2020-09-24 15:43 UTC, hegyhati requested changes
Egy nagyon apro modositas van, azt csinaljatok meg, aztan mehet be. Szerencsere raerunk.

2020-09-24 15:43 UTC, hegyhati commented on character.cpp
> +Character::Character(std::string name, int health, int damage) :name(name), health(health), damage(damage) {}
Ezt miert szedtetek ki?

2020-09-24 15:43 UTC, hegyhati commented on character.cpp
> +	}
Vakartama fejem, mire megertettem, de ok :-D

2020-09-24 15:43 UTC, hegyhati commented on main.cpp
> +	}
Uch, itt az indentalast tegyetek rendbe, az az if-catch-else nekem bantja a szemem. Illetve hiba eseten ne 0-val terjunk vissza.

2020-09-27 14:08 UTC, bartaliszoltan commented
@hegyhati elvégeztük a kért módosításokat.

2020-10-01 12:20 UTC, mogyorosimartin commented
@hegyhati elvégeztük a kért módosításokat.

2020-10-01 16:39 UTC, hegyhati approved these changes

2020-10-01 16:39 UTC, merged