Levelup
Teaching-projects/SZE-MOSZE-2020-Insert_name_here pull request #5
Opened 2020-10-15 00:39 UTC by bartaliszoltan

Added Player class, static code analysis

2020-10-17 13:47 UTC, oliverosz requested changes
OO szempontból elfogadhatatlan a megoldás. Mivel az SCA és a leakcheck rendben van, adok lehetőséget javításra, de ezt a tervet teljesen újra kell gondolni.

2020-10-17 13:47 UTC, oliverosz commented on .github/workflows/test_01.yml
> +        run: g++ -std=c++17 *.cpp
Azért a fordítói warningok is legyenek bekapcsolva, legalább a `-Wall` és a `-Werror` is, hogy ne fogadja el, ha warningot dob a fordító.

2020-10-17 13:47 UTC, oliverosz commented on test_style_and_performance.sh
> +    exit 1
Itt nem kell 1-et visszaadni, mert az leállítja a workflow-t. Ez a fájl csak legyen feltöltve artifactként.

2020-10-17 13:47 UTC, oliverosz commented on character.cpp
> +void Character::reduceHealthByDamage(Character &attacker) {
Nem változott a függvény, miért lett non-const a paraméter?

2020-10-17 13:47 UTC, oliverosz commented on player.cpp
> +void Character::reduceHealthByDamage(Player& attacker) {
Ne a Character viselkedjen másképp, ha egy Player támadja, hanem a támadó viselkedjen a típusának megfelelően.

2020-10-17 13:47 UTC, oliverosz commented on character.h
> +		void reduceHealthByDamage(Player& attacker);
Az ősosztály ne dependeljen a leszármazottjára!

2020-10-17 13:47 UTC, oliverosz commented on game.cpp
> +template void Game::attack <Player, Character>(Player&, Character&);
Ha a headerben, inline módon lenne kifejtve a template függvény, akkor nem kellene explicit példányosítani.

2020-10-17 13:47 UTC, oliverosz commented on player.h
> +	void lvlUp();
Ezeknek nem kéne publikusnak lenniük.

2020-10-17 13:47 UTC, oliverosz commented on player.cpp
> +	xp += this->getDamage();
Nem mindig kéne megkapnia a teljes damage után, csak a ténylegesen bevitt sebzés után, amit az ellenségnek okozott.

2020-10-18 18:45 UTC, bartaliszoltan commented
@oliverosz elvégeztük a kért módosításokat.

2020-10-19 16:00 UTC, oliverosz commented
OK, így már jó a megoldás, most frissíteni kell a branchet a master jelenlegi állapotára, közben meg feloldani a conflictokat.

2020-10-21 01:52 UTC, bartaliszoltan commented
Elvégeztük a merge conflictok feloldását.

2020-10-21 15:00 UTC, oliverosz commented
> @oliverosz Elvégeztük a merge conflictok feloldását.

Én nem látom, nekem továbbra is conflictokat ír ki. És a "merge and fix conflicts" nevű commit nem is egy merge commit. Nem lett bemergelve a master ebbe a branchbe. Azt látom, hogy ebben a commitban bekerültek attackspeedes kódrészletek, de hogyan? Ugye nem kézzel lettek idemásolva?

@bartaliszoltan Az utolsó 2 commitot vagy reverteld, vagy force pushold fel az előtte lévő állapotot, és utána csináld meg rendesen a merge-t.

2020-10-21 18:28 UTC, bartaliszoltan commented
@oliverosz a branchet visszaállítottuk, majd végrehajtottuk a merget és a conflictok feloldását.

2020-10-21 21:15 UTC, oliverosz commented
Most már valóban megtörtént a merge, és már conflictok sem jelennek meg, viszont kitörlődtek a doxygen kommentek a merge során. :( Tovább nem néztem, hogy más is hiányzik-e, de nézzétek át alaposan!

2020-10-22 01:42 UTC, bartaliszoltan commented
@oliverosz a merge során törölt doxygen kommenteket visszaállítottuk.

2020-10-22 09:02 UTC, oliverosz approved these changes

2020-10-22 09:03 UTC, merged