jsonparser
Teaching-projects/SZE-MOSZE-2020-Insert_name_here pull request #6
Opened 2020-10-15 19:45 UTC by mogyorosimartin

added jsonparser and unit tests

2020-10-20 17:06 UTC, wajzy requested changes
Készítsd fel a parzert arra, hogy lehetnek kisebb formai hibák a bemenetben.

2020-10-20 17:06 UTC, wajzy commented on jsonparser.cpp
> +	}
Ezt ne! A kétféle bemenet típusra készüljön két külön függvény!

2020-10-20 17:06 UTC, wajzy commented on jsonparser.cpp
> +				}
Mi a garancia arra, hogy fogsz találni még egy idézőjelet?

2020-10-20 17:06 UTC, wajzy commented on jsonparser.h
> +    static std::map <std::string, std::string> jsonParser(const std::string& file);
Szóval ide kellene egy harmadik fv.

2020-10-20 17:06 UTC, wajzy commented on main.cpp
>  	catch (std::string fileError) {
Praktikusabb lenne referenciát elkapni.

2020-10-21 18:52 UTC, mogyorosimartin commented
@wajzy elvégeztük a kért módosításokat.

2020-10-24 16:49 UTC, wajzy requested changes
Továbbra sem látok olyan tesztesetet, amiben az idézőjel hiánya szerepelne, pl.
"name" : "error,
és még mindig keverednek a feladatok ugyanabban a függvényben, csak most ez a függvény meghív egy másikat is.

2020-10-24 16:49 UTC, wajzy commented on jsonparser.cpp
> +		alldata=jsonParserFILE(fname);
1) Elég zavarba ejtő, hogy a jsonParserFILE egy stringet ad vissza.  Nem erre utal a neve.
2) Az alaphelyzet, hogy jsonParser paramétere lehet egy JSON tartalom, de egy fájl neve is, nem változott meg.

2020-10-24 21:47 UTC, mogyorosimartin commented
@wajzy elvégeztük a kért módosításokat.

2020-10-25 08:37 UTC, wajzy approved these changes
Még mindig értetlenkedek néhol, de sokkal inkább OK, mint nem.

2020-10-25 08:37 UTC, wajzy commented on jsonparser.cpp
> +		if(std::count(line.begin(), line.end(), '"') % 2 == 1) throw std::string("Invalid input formating");
Értem. Tehát akkor a
"name : error",
sor helyes. :)

2020-10-25 08:37 UTC, wajzy commented on character.cpp
> +	}
Miért ragaszkodsz ennyire hozzá, hogy valahol ez az if szerepeljen? Kéri valahol a feladat, hogy legyen egy függvény, ami képes detektálni a paraméter tartalma alapján, hogy az egy fájl neve, vagy egy JSON tartalom, és ennek megfelelően kell működnie?
A karakternek egyelőre elég, ha egy fájlnév (ld. parancssori paraméter) alapján tudja kérni a parzert az adatok betöltésére. A parzer meg most kicsit túl általános is, de ez nem baj, később esetleg át lehet majd tenni egy másik programba, ahol meg a többi függvényére lesz szükség.

2020-10-25 08:37 UTC, wajzy commented
@mogyorosimartin Tessék feloldani az ütközéseket!

2020-10-25 13:07 UTC, mogyorosimartin commented
@wajzy Feloldottuk az ütközéseket

2020-10-27 10:44 UTC, wajzy commented on main.cpp
> +	}
Ez itt nekem minimum fura. Miért kell a konkrét fájlnévtől függően mindig más osztályból példányosítani?

2020-10-27 13:29 UTC, bartaliszoltan commented
@wajzy Ezt csak ideiglenes megoldásnak szántuk a levelup branchen a szintlépések tesztelése miatt. Javítottuk, most a main az első beolvasott fájlból/stringből Playert, a másodikból Charactert hoz létre.

2020-10-31 09:33 UTC, merged